### PR TITLE
Force pulse update for liquid decorations

### PR DESCRIPTION
**Pull request by mastercoms**
Pulls into https://github.com/deathcap/GlowstonePlusPlus/pull/30
to fix https://github.com/deathcap/GlowstonePlusPlus/issues/27

### CODE REVIEW

**Comment by jimmikaelkael** [comment]
Why the pulse can't be done in GlowBlock.applyPhysics method ?

**Comment by mastercoms** [comment]
Laziness. :stuck_out_tongue:

**Comment by jimmikaelkael** [comment]
I think it'll solve the problem equally, and comply with physics update asked from bukkit api. Maybe I'm wrong...

**Comment by mastercoms** [comment]
Yeah, you're right. I'll fix it in Glowkit.

**Comment by jimmikaelkael** [comment]
I don't think Glowkit needs to be modified, adding code to pulse in GlowBlock.applyPhysics method should be sufficient.
Again I can be wrong.

**Comment by mastercoms** [comment]
Ok.

**Comment by mastercoms** [comment]
Ok, it should fix the problem. I guess just merge it and then we'll test it in the main repo.

**Comment by jimmikaelkael** [comment]
OK

**Pull request merged**
